### ISSUE TITLE
What about lucid icons pack for qwik? 

### ISSUE THREAD

**Issue by piscopancer** [iancharlesdouglas/carbon-icons-qwik#1]
Can you do it? Lucid icons are awesome, the total number is enormous though, must be a lot of work 🤔

**Comment by iancharlesdouglas** [comment]
It could probably be done fairly easily -- I'll bear it in mind for the future.  But I created this carbon-icons-qwik library because I'm in the process of implementing Carbon Design System components for Qwik.
